Update CI Configuration
RockefellerArchiveCenter/pisces pull request #469
Opened 2021-09-27 20:40 UTC by HaSistrunk

- Updates README mention of pre-commit configs to be consistent with other repos.
- Updates Travis CI configs
- Updates dependencies

Noticing the build time is > 5 min, so I'll add an issue about that.

2021-09-27 20:47 UTC, helrond requested changes

2021-09-27 20:47 UTC, helrond commented on .travis.yml
> +  - docker-compose exec $CONTAINER coverage xml
You don't need this line. This just creates an XML version of the coverage report, which we used to ship off to Code Climate but don't anymore. https://coverage.readthedocs.io/en/coverage-5.5/cmd.html#cmd-xml

2021-09-27 22:32 UTC, helrond approved these changes

2021-09-28 15:52 UTC, p-galligan approved these changes

2021-09-28 18:04 UTC, bonniegee approved these changes

2021-09-28 20:03 UTC, merged