Updates CI Tooling
RockefellerArchiveCenter/pisces pull request #475
Opened 2021-12-08 15:11 UTC by p-galligan

Updates CI tooling for enhanced deployment.

2021-12-08 19:09 UTC, helrond requested changes
A couple of minor things...

2021-12-08 19:09 UTC, helrond commented on appspec.yml.deploy
> +    - location: deploy_scripts/curl_index.sh
I believe you could CURL the status endpoint? That's a slightly stronger test because it checks the various system components.

2021-12-08 19:09 UTC, helrond commented on pisces/config.py.deploy
> +APPLICATION_PORT = ${APPLICATION_PORT}
Does the application actually need this variable? Is it used anywhere in Django?

2021-12-08 19:51 UTC, helrond approved these changes

2021-12-08 21:21 UTC, helrond commented
@p-galligan please hold off on merging this until later next week - we need a fetch of archival objects to finish first. I think it will be done by Monday, but check in with me first.

2021-12-09 22:07 UTC, bonniegee approved these changes

2021-12-10 14:15 UTC, HaSistrunk approved these changes

2021-12-10 16:22 UTC, merged